gui:
  sidePanelWidth: 0.2
  showBottomLine: false
  showPanelJumps: false
  nerdFontsVersion: "3"
  border: single
  theme:
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - "#2a2b3c"
git:
  paging:
    pager: delta --dark --paging=never --side-by-side --line-numbers-left-format="" --line-numbers-right-format="│ "
keybinding:
  universal:
    copyToClipboard: "y"
    undo: u
    redo: U
quitOnTopLevelReturn: true
notARepository: quit
promptToReturnFromSubprocess: false
