"$schema" = "https://starship.rs/config-schema.json"

# add_newline = false
format = """
$directory\
$git_branch\
$python\
$character\
"""
right_format = """
$cmd_duration\
"""

[directory]
disabled = false
truncation_length = 8
truncation_symbol = "/"
truncate_to_repo = false
format = "[$path ](white)"

[git_branch]
disabled = false
symbol = ""
always_show_remote = true
format = "[$symbol $branch ](green)"

[python]
disabled = false
symbol = "󰌠"
format = '[$symbol ($version )(\($virtualenv\) )](blue)'

[cmd_duration]
disabled = false
show_milliseconds = true
format = "[$duration](yellow)"
